// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAkEx2FQSIFbEgXHcjlGn1vPOFNGV5Xc',
    appId: '1:230210205202:web:9138adaafc376370430acb',
    messagingSenderId: '230210205202',
    projectId: 'yamudacarpool-8529c',
    authDomain: 'yamudacarpool-8529c.firebaseapp.com',
    databaseURL: 'https://yamudacarpool-8529c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yamudacarpool-8529c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YZ6feHtH-6wN0inOIFS7N-mZu8Df2iU',
    appId: '1:230210205202:android:ef36693e2f91e51d430acb',
    messagingSenderId: '230210205202',
    projectId: 'yamudacarpool-8529c',
    databaseURL: 'https://yamudacarpool-8529c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yamudacarpool-8529c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaBEwcNgpsp6qkljYStoCOI9j32t4Ihk',
    appId: '1:230210205202:ios:b60e8b39d434d4f9430acb',
    messagingSenderId: '230210205202',
    projectId: 'yamudacarpool-8529c',
    databaseURL: 'https://yamudacarpool-8529c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yamudacarpool-8529c.appspot.com',
    iosBundleId: 'com.example.yamudacarpooling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaBEwcNgpsp6qkljYStoCOI9j32t4Ihk',
    appId: '1:230210205202:ios:476ea2f76815ba5e430acb',
    messagingSenderId: '230210205202',
    projectId: 'yamudacarpool-8529c',
    databaseURL: 'https://yamudacarpool-8529c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yamudacarpool-8529c.appspot.com',
    iosBundleId: 'com.example.yamudacarpooling.RunnerTests',
  );
}
